<?php

namespace Database\Seeders;

use App\Models\Mahasiswa;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class MahasiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mahasiswaData = [
            [
                'npm' => '24311329',
                'nama' => 'Lutfi Selamanya',
                'nomor_wa' => '0857658425',
                'jk' => 'laki-laki',
                'password' => Hash::make('24311329'),
                'jurusan_id' => 6,
                'kelas_id' => 6,
                'dosen_id' => 1,
                'gelombang_id' => 12,
                'kelancaran_mengaji' => 'Lancar',
                'jadwal_kuliah' => 'jadwal.jpg',
                'keterangan' => null,
                'pilgan' => null,
                'makhroj' => null,
                'tajwid' => null,
            ],
            [
                'npm' => '24311330',
                'nama' => 'Rizal Hakim',
                'nomor_wa' => '0812345678',
                'jk' => 'laki-laki',
                'password' => Hash::make('24311330'),
                'jurusan_id' => 6,
                'kelas_id' => 6,
                'dosen_id' => 1,
                'gelombang_id' => 12,
                'kelancaran_mengaji' => 'Lancar',
                'jadwal_kuliah' => 'jadwal.jpg',
                'keterangan' => null,
                'pilgan' => null,
                'makhroj' => null,
                'tajwid' => null,
            ],
            [
                'npm' => '24311331',
                'nama' => 'Ahmad Fauzi',
                'nomor_wa' => '0823456789',
                'jk' => 'laki-laki',
                'password' => Hash::make('24311331'),
                'jurusan_id' => 6,
                'kelas_id' => 6,
                'dosen_id' => 1,
                'gelombang_id' => 12,
                'kelancaran_mengaji' => 'Lancar',
                'jadwal_kuliah' => 'jadwal.jpg',
                'keterangan' => null,
                'pilgan' => null,
                'makhroj' => null,
                'tajwid' => null,
            ],
            [
                'npm' => '24311332',
                'nama' => 'Siti Aisyah',
                'nomor_wa' => '0834567890',
                'jk' => 'perempuan',
                'password' => Hash::make('24311332'),
                'jurusan_id' => 6,
                'kelas_id' => 6,
                'dosen_id' => 1,
                'gelombang_id' => 12,
                'kelancaran_mengaji' => 'Lancar',
                'jadwal_kuliah' => 'jadwal.jpg',
                'keterangan' => null,
                'pilgan' => null,
                'makhroj' => null,
                'tajwid' => null,
            ],
            [
                'npm' => '24311333',
                'nama' => 'Budi Santoso',
                'nomor_wa' => '0845678901',
                'jk' => 'laki-laki',
                'password' => Hash::make('24311333'),
                'jurusan_id' => 6,
                'kelas_id' => 6,
                'dosen_id' => 1,
                'gelombang_id' => 12,
                'kelancaran_mengaji' => 'Lancar',
                'jadwal_kuliah' => 'jadwal.jpg',
                'keterangan' => null,
                'pilgan' => null,
                'makhroj' => null,
                'tajwid' => null,
            ],
            [
                'npm' => '24311334',
                'nama' => 'Dina Oktaviani',
                'nomor_wa' => '0856789012',
                'jk' => 'perempuan',
                'password' => Hash::make('24311334'),
                'jurusan_id' => 6,
                'kelas_id' => 6,
                'dosen_id' => 1,
                'gelombang_id' => 12,
                'kelancaran_mengaji' => 'Sedang',
                'jadwal_kuliah' => 'jadwal.jpg',
                'keterangan' => null,
                'pilgan' => null,
                'makhroj' => null,
                'tajwid' => null,
            ],
            [
                'npm' => '24311335',
                'nama' => 'Heri Susanto',
                'nomor_wa' => '0867890123',
                'jk' => 'laki-laki',
                'password' => Hash::make('24311335'),
                'jurusan_id' => 6,
                'kelas_id' => 6,
                'dosen_id' => 1,
                'gelombang_id' => 12,
                'kelancaran_mengaji' => 'Kurang',
                'jadwal_kuliah' => 'jadwal.jpg',
                'keterangan' => null,
                'pilgan' => null,
                'makhroj' => null,
                'tajwid' => null,
            ],
            [
                'npm' => '24311336',
                'nama' => 'Fauzan Hakim',
                'nomor_wa' => '0878901234',
                'jk' => 'laki-laki',
                'password' => Hash::make('24311336'),
                'jurusan_id' => 6,
                'kelas_id' => 6,
                'dosen_id' => 1,
                'gelombang_id' => 12,
                'kelancaran_mengaji' => 'Lancar',
                'jadwal_kuliah' => 'jadwal.jpg',
                'keterangan' => null,
                'pilgan' => null,
                'makhroj' => null,
                'tajwid' => null,
            ],
            [
                'npm' => '24311337',
                'nama' => 'Rina Ayu',
                'nomor_wa' => '0889012345',
                'jk' => 'perempuan',
                'password' => Hash::make('24311337'),
                'jurusan_id' => 6,
                'kelas_id' => 6,
                'dosen_id' => 1,
                'gelombang_id' => 12,
                'kelancaran_mengaji' => 'Sedang',
                'jadwal_kuliah' => 'jadwal.jpg',
                'keterangan' => null,
                'pilgan' => null,
                'makhroj' => null,
                'tajwid' => null,
            ],
            [
                'npm' => '24311338',
                'nama' => 'Bayu Pratama',
                'nomor_wa' => '0890123456',
                'jk' => 'laki-laki',
                'password' => Hash::make('24311338'),
                'jurusan_id' => 6,
                'kelas_id' => 6,
                'dosen_id' => 1,
                'gelombang_id' => 12,
                'kelancaran_mengaji' => 'Lancar',
                'jadwal_kuliah' => 'jadwal.jpg',
                'keterangan' => null,
                'pilgan' => null,
                'makhroj' => null,
                'tajwid' => null,
            ],
            [
                'npm' => '24311339',
                'nama' => 'Sari Kusuma',
                'nomor_wa' => '0891234567',
                'jk' => 'perempuan',
                'password' => Hash::make('24311339'),
                'jurusan_id' => 6,
                'kelas_id' => 6,
                'dosen_id' => 1,
                'gelombang_id' => 12,
                'kelancaran_mengaji' => 'Kurang',
                'jadwal_kuliah' => 'jadwal.jpg',
                'keterangan' => null,
                'pilgan' => null,
                'makhroj' => null,
                'tajwid' => null,
            ],
        ];


        foreach ($mahasiswaData as $data) {
            $mahasiswa = Mahasiswa::create($data);

            User::create([
                'name' => $mahasiswa->nama,
                'username' => $mahasiswa->npm,
                'role' => 'mahasiswa',
                'jenis_kelamin' => $mahasiswa->jk,
                'no_wa' => $mahasiswa->nomor_wa,
                'password' => Hash::make($mahasiswa->npm),
                'email' => strtolower(str_replace(' ', '', $mahasiswa->nama)) . '@example.com',
                'email_verified_at' => now(),
                'remember_token' => null,
            ]);
        }
    }
}
